import { createClient } from "npm:@supabase/supabase-js@2.116.0";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:corsHeaders});
const url=Deno.env.get("SUPABASE_URL")!;
const publicKeys=JSON.parse(Deno.env.get("SUPABASE_PUBLISHABLE_KEYS")!);
const secretKeys=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")!);
const pub=publicKeys.default, secret=secretKeys.default;
const admin=createClient(url,secret,{auth:{autoRefreshToken:false,persistSession:false,detectSessionInUrl:false}});
const userClient=(authorization:string)=>createClient(url,pub,{global:{headers:{Authorization:authorization}},auth:{autoRefreshToken:false,persistSession:false,detectSessionInUrl:false}});
const MANAGEMENT_ROLES=["staff","manager","owner"];

async function context(req:Request){
  const authorization=req.headers.get("Authorization")??"";
  const token=authorization.replace(/^Bearer\s+/i,"");
  if(!token)throw new Error("Authentication is required.");
  const {data,error}=await userClient(authorization).auth.getUser(token);
  if(error||!data.user)throw new Error("Your session is invalid or expired.");
  const {data:links,error:roleError}=await admin.from("vmc_user_roles").select("role:vmc_roles(name)").eq("user_id",data.user.id);
  if(roleError)throw roleError;
  const role=(links??[]).map((r:any)=>r.role?.name).find((r:string)=>MANAGEMENT_ROLES.includes(r));
  if(!role)throw new Error("Management access is required.");
  const {data:profile,error:profileError}=await admin.from("vmc_profiles").select("id,full_name,username,email,phone,account_status").eq("id",data.user.id).single();
  if(profileError||!profile||profile.account_status!=="active")throw new Error("This management account is not active.");
  return {userId:data.user.id,role,profile};
}
function requireRole(role:string,allowed:string[]){if(!allowed.includes(role))throw new Error("You do not have permission for this action.");}
function today(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Blantyre",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function addDuration(start:string,count:number,unit:string){const d=new Date(start+"T00:00:00Z");if(unit==="day")d.setUTCDate(d.getUTCDate()+count-1);else if(unit==="week")d.setUTCDate(d.getUTCDate()+count*7-1);else if(unit==="month"){const original=d.getUTCDate();d.setUTCMonth(d.getUTCMonth()+count);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(original,last)-1)}else throw new Error("Invalid membership duration.");return d.toISOString().slice(0,10)}
async function audit(actorId:string,action:string,entityType:string,entityId:string|null,metadata:any={}){const{error}=await admin.from("vmc_audit_logs").insert({actor_id:actorId,action,entity_type:entityType,entity_id:entityId,metadata});if(error)console.error("VMC audit log failed:",error)}
async function memberIds(){const{data:role,error}=await admin.from("vmc_roles").select("id").eq("name","member").single();if(error||!role)throw error??new Error("Member role is not configured.");const{data,error:e}=await admin.from("vmc_user_roles").select("user_id").eq("role_id",role.id);if(e)throw e;return(data??[]).map((x:any)=>x.user_id)}
async function members(){const ids=await memberIds();if(!ids.length)return{members:[]};const[profiles,memberships]=await Promise.all([admin.from("vmc_profiles").select("id,full_name,username,phone,email,account_status,created_at").in("id",ids).order("created_at",{ascending:false}),admin.from("vmc_memberships").select("id,member_id,start_date,end_date,status,training_mode,created_at,plan:vmc_membership_plans(name,duration_unit,duration_count,session_type,price)").in("member_id",ids).order("created_at",{ascending:false})]);if(profiles.error)throw profiles.error;if(memberships.error)throw memberships.error;const latest=new Map<string,any>();for(const m of memberships.data??[])if(!latest.has(m.member_id))latest.set(m.member_id,m);return{members:(profiles.data??[]).map((p:any)=>({...p,membership:latest.get(p.id)??null}))}}
async function payments(){const ids=await memberIds();if(!ids.length)return{payments:[]};const[r,m,p]=await Promise.all([admin.from("vmc_profiles").select("id,full_name").in("id",ids),admin.from("vmc_memberships").select("id,member_id,plan:vmc_membership_plans(name,duration_unit,duration_count,session_type,price)").in("member_id",ids),admin.from("vmc_payments").select("id,member_id,membership_id,amount,payment_method,receipt_reference,payment_date,status,verified_at,created_at").in("member_id",ids).order("payment_date",{ascending:false}).limit(500)]);for(const x of[r,m,p])if(x.error)throw x.error;const names=new Map((r.data??[]).map((x:any)=>[x.id,x.full_name]));const memberships=new Map((m.data??[]).map((x:any)=>[x.id,x]));return{payments:(p.data??[]).map((x:any)=>({...x,member_name:names.get(x.member_id)??"Unknown member",membership:memberships.get(x.membership_id)??null}))}}
async function attendance(){const ids=await memberIds();if(!ids.length)return{attendance:[],members:[]};const[r,a]=await Promise.all([admin.from("vmc_profiles").select("id,full_name").in("id",ids).order("full_name"),admin.from("vmc_attendance").select("id,member_id,checked_in_at,checked_out_at,recorded_by,created_at").in("member_id",ids).order("checked_in_at",{ascending:false}).limit(500)]);if(r.error)throw r.error;if(a.error)throw a.error;const names=new Map((r.data??[]).map((x:any)=>[x.id,x.full_name]));const actorIds=[...new Set((a.data??[]).map((x:any)=>x.recorded_by).filter(Boolean))];let actorNames=new Map<string,string>();if(actorIds.length){const{data:actors}=await admin.from("vmc_profiles").select("id,full_name").in("id",actorIds);actorNames=new Map((actors??[]).map((x:any)=>[x.id,x.full_name]))}return{members:r.data??[],attendance:(a.data??[]).map((x:any)=>({...x,member_name:names.get(x.member_id)??"Unknown member",recorded_by_name:x.recorded_by?actorNames.get(x.recorded_by)??"VMC staff":"VMC staff"}))}}
async function reports(){const ids=await memberIds();if(!ids.length)return{stats:{totalMembers:0,activeMembers:0,pendingPayments:0,verifiedRevenue:0,totalVisits:0},months:[]};const[r,m,p,a]=await Promise.all([admin.from("vmc_profiles").select("id,account_status").in("id",ids),admin.from("vmc_memberships").select("member_id,status,end_date,created_at").in("member_id",ids).order("created_at",{ascending:false}),admin.from("vmc_payments").select("amount,status,payment_date").in("member_id",ids).order("payment_date",{ascending:false}).limit(1000),admin.from("vmc_attendance").select("checked_in_at").in("member_id",ids).limit(2000)]);for(const x of[r,m,p,a])if(x.error)throw x.error;const latest=new Map<string,any>();for(const x of m.data??[])if(!latest.has(x.member_id))latest.set(x.member_id,x);const t=today();const active=(r.data??[]).filter((x:any)=>x.account_status==="active"&&latest.get(x.id)?.status==="active"&&String(latest.get(x.id)?.end_date||"")>=t).length;const verifiedRevenue=(p.data??[]).filter((x:any)=>x.status==="verified").reduce((s:number,x:any)=>s+Number(x.amount||0),0);const pending=(p.data??[]).filter((x:any)=>x.status==="pending").length;const monthMap=new Map<string,{visits:number,revenue:number}>();for(const x of a.data??[]){const key=String(x.checked_in_at).slice(0,7);const v=monthMap.get(key)||{visits:0,revenue:0};v.visits++;monthMap.set(key,v)}for(const x of p.data??[]){if(x.status!=="verified")continue;const key=String(x.payment_date).slice(0,7);const v=monthMap.get(key)||{visits:0,revenue:0};v.revenue+=Number(x.amount||0);monthMap.set(key,v)}const months=[...monthMap.entries()].sort((a,b)=>b[0].localeCompare(a[0])).slice(0,6).map(([month,v])=>({month,visits:v.visits,revenue:v.revenue}));return{stats:{totalMembers:r.data?.length??0,activeMembers:active,pendingPayments:pending,verifiedRevenue,totalVisits:a.data?.length??0},months}}
async function staff(){const{data:roles,error}=await admin.from("vmc_roles").select("id,name").in("name",["staff","manager","owner"]);if(error)throw error;const roleMap=new Map((roles??[]).map((r:any)=>[r.id,r.name]));const ids=[...(await admin.from("vmc_user_roles").select("user_id,role_id").in("role_id",[...roleMap.keys()])).data??[]];if(!ids.length)return{staff:[]};const{data:profiles,error:e}=await admin.from("vmc_profiles").select("id,full_name,username,email,phone,account_status,created_at").in("id",ids.map((x:any)=>x.user_id)).order("created_at",{ascending:false});if(e)throw e;const roleByUser=new Map(ids.map((x:any)=>[x.user_id,roleMap.get(x.role_id)]));return{staff:(profiles??[]).map((p:any)=>({...p,role:roleByUser.get(p.id)||"unknown"}))}}
async function updatePayment(actorId:string,paymentId:string,status:"verified"|"rejected"){requireRole((await actorRole(actorId)),["staff","manager","owner"]);const{data:p,error}=await admin.from("vmc_payments").select("id,member_id,membership_id,amount,status").eq("id",paymentId).maybeSingle();if(error)throw error;if(!p)throw new Error("Payment record not found.");if(p.status!=="pending")throw new Error("This payment has already been reviewed.");const{data:m,error:me}=await admin.from("vmc_memberships").select("id,member_id,plan_id,status,start_date,end_date,plan:vmc_membership_plans(duration_unit,duration_count,session_type,price)").eq("id",p.membership_id).maybeSingle();if(me)throw me;if(!m)throw new Error("Membership record not found.");const now=new Date().toISOString();if(status==="rejected"){const{error:e}=await admin.from("vmc_payments").update({status:"rejected",verified_by:actorId,verified_at:now}).eq("id",paymentId).eq("status","pending");if(e)throw e;const{error:e2}=await admin.from("vmc_memberships").update({status:"cancelled",updated_at:now}).eq("id",m.id);if(e2)throw e2;await audit(actorId,"payment_rejected","payment",paymentId,{membership_id:m.id,amount:p.amount});return{ok:true,status}}const t=today();const{data:active,error:ae}=await admin.from("vmc_memberships").select("end_date").eq("member_id",p.member_id).eq("status","active").gte("end_date",t).order("end_date",{ascending:false}).limit(1).maybeSingle();if(ae)throw ae;const start=active?.end_date?new Date(active.end_date+"T00:00:00Z"):new Date(t+"T00:00:00Z");if(active)start.setUTCDate(start.getUTCDate()+1);const startDate=start.toISOString().slice(0,10);const plan=m.plan as any;const end=addDuration(startDate,Number(plan.duration_count||1),String(plan.duration_unit));const{error:e}=await admin.from("vmc_payments").update({status:"verified",verified_by:actorId,verified_at:now}).eq("id",paymentId).eq("status","pending");if(e)throw e;const{error:e2}=await admin.from("vmc_memberships").update({status:"active",start_date:startDate,end_date:end,updated_at:now}).eq("id",m.id);if(e2)throw e2;await audit(actorId,"payment_verified","payment",paymentId,{membership_id:m.id,amount:p.amount,start_date:startDate,end_date:end});return{ok:true,status,start_date:startDate,end_date:end}}
async function actorRole(userId:string){const{data}=await admin.from("vmc_user_roles").select("role:vmc_roles(name)").eq("user_id",userId);return(data??[]).map((x:any)=>x.role?.name).find(Boolean)||""}
async function setAccountStatus(actorId:string,userId:string,status:string){const role=await actorRole(actorId);requireRole(role,["manager","owner"]);if(actorId===userId)throw new Error("You cannot change your own management access.");if(!["active","suspended","deactivated"].includes(status))throw new Error("Invalid account status.");const targetRole=await actorRole(userId);if(targetRole!=="member")throw new Error("Only member accounts can be changed here.");const{error}=await admin.from("vmc_profiles").update({account_status:status,updated_at:new Date().toISOString()}).eq("id",userId);if(error)throw error;await audit(actorId,"member_status_changed","profile",userId,{to:status});return{ok:true,status}}
async function checkIn(actorId,memberId:string){requireRole(await actorRole(actorId),["staff","manager","owner"]);const role=await actorRole(memberId);if(role!=="member")throw new Error("Only member accounts can be checked in.");const{data:open}=await admin.from("vmc_attendance").select("id").eq("member_id",memberId).is("checked_out_at",null).order("checked_in_at",{ascending:false}).limit(1).maybeSingle();if(open)throw new Error("This member is already checked in.");const{data:m}=await admin.from("vmc_memberships").select("status,end_date").eq("member_id",memberId).eq("status","active").order("created_at",{ascending:false}).limit(1).maybeSingle();if(!m||!m.end_date||m.end_date<today())throw new Error("This member does not have an active membership.");const{data,error}=await admin.from("vmc_attendance").insert({member_id:memberId,recorded_by:actorId}).select("id,checked_in_at").single();if(error)throw error;await audit(actorId,"attendance_check_in","attendance",data.id,{member_id:memberId});return{ok:true,attendance:data}}
async function checkOut(actorId,attendanceId:string){requireRole(await actorRole(actorId),["staff","manager","owner"]);const{data,error:rowError}=await admin.from("vmc_attendance").select("id,member_id,checked_out_at").eq("id",attendanceId).maybeSingle();if(rowError)throw rowError;if(!data)throw new Error("Attendance record not found.");if(data.checked_out_at)throw new Error("This attendance record is already closed.");const{data:updated,error}=await admin.from("vmc_attendance").update({checked_out_at:new Date().toISOString()}).eq("id",attendanceId).is("checked_out_at",null).select("id,checked_out_at").single();if(error)throw error;await audit(actorId,"attendance_check_out","attendance",attendanceId,{member_id:data.member_id});return{ok:true,attendance:updated}}
async function createManagementUser(actorId:string,body:any){requireRole(await actorRole(actorId),["owner"]);const fullName=typeof body.full_name==="string"?body.full_name.trim():"";const email=typeof body.email==="string"&&body.email.trim()?body.email.trim().toLowerCase():null;const phone=typeof body.phone==="string"&&body.phone.trim()?body.phone.replace(/[^+\d]/g,""):null;const role=String(body.role||"").trim();if(fullName.length<2)throw new Error("Enter a valid full name.");if(!email&&!phone)throw new Error("Provide an email or phone number.");if(!["staff","manager","owner"].includes(role))throw new Error("Choose a valid management role.");if(email){const{data}=await admin.from("vmc_profiles").select("id").eq("email",email).maybeSingle();if(data)throw new Error("That email is already registered.")}if(phone){const{data}=await admin.from("vmc_profiles").select("id").eq("phone",phone).maybeSingle();if(data)throw new Error("That phone number is already registered.")}const password=(()=>{const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";let s="";for(const b of bytes)s+=alphabet[b%alphabet.length];return s.slice(0,12)+"!9"})();const{data,error}=await admin.auth.admin.createUser({email:email??undefined,phone:phone??undefined,password,email_confirm:Boolean(email),phone_confirm:Boolean(phone),user_metadata:{full_name:fullName,must_change_password:true}});if(error||!data.user)throw new Error("Could not create the management account.");const id=data.user.id;try{const{error:e}=await admin.from("vmc_profiles").update({full_name:fullName,email,phone,must_change_password:true,account_status:"active"}).eq("id",id);if(e)throw e;const{data:r,error:re}=await admin.from("vmc_roles").select("id").eq("name",role).single();if(re||!r)throw re??new Error("Role is not configured.");const{error:ue}=await admin.from("vmc_user_roles").upsert({user_id:id,role_id:r.id},{onConflict:"user_id"});if(ue)throw ue;await audit(actorId,"management_account_created","profile",id,{role});return{ok:true,user_id:id,role,temporary_password:password}}catch(e){await admin.auth.admin.deleteUser(id);throw e}}
async function deleteAccount(actorId:string,userId:string){requireRole(await actorRole(actorId),["owner"]);if(actorId===userId)throw new Error("You cannot delete your own account.");const role=await actorRole(userId);if(!["member","staff","manager"].includes(role))throw new Error("Owner accounts cannot be deleted from this screen.");await audit(actorId,"account_deleted",role,userId,{});const{error}=await admin.auth.admin.deleteUser(userId);if(error)throw error;return{ok:true}}
async function dashboard(){const r=await reports();return r}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"POST required."},405);try{const ctx=await context(req);const body=await req.json().catch(()=>({}));const action=String(body.action||"");if(action==="dashboard")return json(await dashboard());if(action==="members")return json(await members());if(action==="payments")return json(await payments());if(action==="attendance")return json(await attendance());if(action==="reports")return json(await reports());if(action==="staff")return json({...await staff(),role:ctx.role});if(action==="verify_payment")return json(await updatePayment(ctx.userId,String(body.payment_id||""),"verified"));if(action==="reject_payment")return json(await updatePayment(ctx.userId,String(body.payment_id||""),"rejected"));if(action==="set_account_status")return json(await setAccountStatus(ctx.userId,String(body.user_id||""),String(body.status||"")));if(action==="check_in")return json(await checkIn(ctx.userId,String(body.member_id||"")));if(action==="check_out")return json(await checkOut(ctx.userId,String(body.attendance_id||"")));if(action==="create_management_user")return json(await createManagementUser(ctx.userId,body));if(action==="delete_account")return json(await deleteAccount(ctx.userId,String(body.user_id||"")));return json({error:"Unsupported management action."},400)}catch(error){console.error("VMC management API v2 error:",error);return json({error:String((error as any)?.message??error)},400)}});
